/**
 * Curated extra icons for author-customized admonitions.
 *
 * Authors pick an icon with a parenthetical attribute on the label, e.g.
 * `**Note (icon=flame):**`. The set is deliberately small — the full Lucide
 * library would add a ~1.4MB chunk to the app bundle. Admonition icons are
 * baked into exported HTML as inline SVG at export time, so this module is
 * never reached by the export runtime bundle.
 */

import {
  Award,
  Bell,
  Bookmark,
  BookOpen,
  Bug,
  Calendar,
  Camera,
  Check,
  Clock,
  Coffee,
  Compass,
  Crown,
  Feather,
  FileQuestionMark,
  Flag,
  Flame,
  Gem,
  Globe,
  GraduationCap,
  Heart,
  HelpCircle,
  Hourglass,
  Image,
  Inbox,
  Key,
  Link,
  Lock,
  Map,
  MapPin,
  Megaphone,
  MessageCircle,
  Mic,
  Moon,
  Paperclip,
  Pencil,
  Percent,
  Puzzle,
  Rocket,
  Search,
  Send,
  Shield,
  ShoppingCart,
  Star,
  Sun,
  Tag,
  Target,
  Telescope,
  ThumbsUp,
  Timer,
  Trophy,
  Umbrella,
  Users,
  Watch,
  Wifi,
  Wrench,
  Zap,
} from "lucide";

export const ADMONITION_EXTRA_ICONS = Object.freeze({
  award: Award,
  bell: Bell,
  bookmark: Bookmark,
  "book-open": BookOpen,
  bug: Bug,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  clock: Clock,
  coffee: Coffee,
  compass: Compass,
  crown: Crown,
  feather: Feather,
  "file-question-mark": FileQuestionMark,
  flag: Flag,
  flame: Flame,
  gem: Gem,
  globe: Globe,
  "graduation-cap": GraduationCap,
  heart: Heart,
  "help-circle": HelpCircle,
  hourglass: Hourglass,
  image: Image,
  inbox: Inbox,
  key: Key,
  link: Link,
  lock: Lock,
  map: Map,
  "map-pin": MapPin,
  megaphone: Megaphone,
  "message-circle": MessageCircle,
  mic: Mic,
  moon: Moon,
  paperclip: Paperclip,
  pencil: Pencil,
  percent: Percent,
  puzzle: Puzzle,
  rocket: Rocket,
  search: Search,
  send: Send,
  shield: Shield,
  "shopping-cart": ShoppingCart,
  star: Star,
  sun: Sun,
  tag: Tag,
  target: Target,
  telescope: Telescope,
  "thumbs-up": ThumbsUp,
  timer: Timer,
  trophy: Trophy,
  umbrella: Umbrella,
  users: Users,
  watch: Watch,
  wifi: Wifi,
  wrench: Wrench,
  zap: Zap,
});
