/**
 * Curated extra icons for author-customized callouts.
 *
 * Authors pick an icon with a parenthetical attribute on the label, e.g.
 * `**Heads up (icon=flame):**`. The set is deliberately bounded — the full
 * Lucide library would add a ~1.4MB chunk to the app bundle. Callout icons
 * are baked into exported HTML as inline SVG at export time, so this module
 * is never reached by the export runtime bundle.
 *
 * `history` aliases ClockFading: Lucide dropped the old History glyph, and
 * this keeps books written against the familiar name working.
 */

import {
  Anchor,
  Atom,
  Award,
  Bell,
  Binoculars,
  Bookmark,
  Book,
  BookOpen,
  Bot,
  Box,
  Brain,
  Briefcase,
  Bug,
  Calculator,
  Calendar,
  Camera,
  Car,
  ChartColumn,
  Check,
  Clock,
  ClockFading,
  Cloud,
  Code,
  Coffee,
  Compass,
  Crown,
  Database,
  Download,
  Eye,
  Feather,
  FileQuestionMark,
  FileText,
  FingerprintPattern,
  Flag,
  Flame,
  Footprints,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Heart,
  HelpCircle,
  Highlighter,
  House,
  Hourglass,
  Image,
  Inbox,
  Key,
  Languages,
  Laptop,
  Leaf,
  Library,
  Link,
  Lock,
  Mail,
  Map,
  MapPin,
  Medal,
  Megaphone,
  MessageCircle,
  Microscope,
  Mic,
  Moon,
  Mountain,
  Music,
  Newspaper,
  Palette,
  Paperclip,
  PawPrint,
  Pencil,
  PenTool,
  Percent,
  Phone,
  Plane,
  Presentation,
  Printer,
  Puzzle,
  Rocket,
  Ruler,
  Scale,
  Scissors,
  Search,
  Send,
  Shield,
  ShoppingCart,
  Sprout,
  Star,
  Stethoscope,
  Sun,
  Tag,
  Target,
  Telescope,
  Ticket,
  TrainFront,
  TreePine,
  ThumbsUp,
  Timer,
  Trophy,
  Umbrella,
  Users,
  Watch,
  Waypoints,
  Wifi,
  Wrench,
  Zap,
} from "lucide";

export const ADMONITION_EXTRA_ICONS = Object.freeze({
  anchor: Anchor,
  atom: Atom,
  award: Award,
  bell: Bell,
  binoculars: Binoculars,
  bookmark: Bookmark,
  book: Book,
  "book-open": BookOpen,
  bot: Bot,
  box: Box,
  brain: Brain,
  briefcase: Briefcase,
  bug: Bug,
  calculator: Calculator,
  calendar: Calendar,
  camera: Camera,
  car: Car,
  "chart-column": ChartColumn,
  check: Check,
  clock: Clock,
  history: ClockFading,
  cloud: Cloud,
  code: Code,
  coffee: Coffee,
  compass: Compass,
  crown: Crown,
  database: Database,
  download: Download,
  eye: Eye,
  feather: Feather,
  "file-question-mark": FileQuestionMark,
  "file-text": FileText,
  "fingerprint-pattern": FingerprintPattern,
  flag: Flag,
  flame: Flame,
  footprints: Footprints,
  gem: Gem,
  gift: Gift,
  globe: Globe,
  "graduation-cap": GraduationCap,
  heart: Heart,
  "help-circle": HelpCircle,
  highlighter: Highlighter,
  house: House,
  hourglass: Hourglass,
  image: Image,
  inbox: Inbox,
  key: Key,
  languages: Languages,
  laptop: Laptop,
  leaf: Leaf,
  library: Library,
  link: Link,
  lock: Lock,
  mail: Mail,
  map: Map,
  "map-pin": MapPin,
  medal: Medal,
  megaphone: Megaphone,
  "message-circle": MessageCircle,
  microscope: Microscope,
  mic: Mic,
  moon: Moon,
  mountain: Mountain,
  music: Music,
  newspaper: Newspaper,
  palette: Palette,
  paperclip: Paperclip,
  "paw-print": PawPrint,
  pencil: Pencil,
  "pen-tool": PenTool,
  percent: Percent,
  phone: Phone,
  plane: Plane,
  presentation: Presentation,
  printer: Printer,
  puzzle: Puzzle,
  rocket: Rocket,
  ruler: Ruler,
  scale: Scale,
  scissors: Scissors,
  search: Search,
  send: Send,
  shield: Shield,
  "shopping-cart": ShoppingCart,
  sprout: Sprout,
  star: Star,
  stethoscope: Stethoscope,
  sun: Sun,
  tag: Tag,
  target: Target,
  telescope: Telescope,
  ticket: Ticket,
  "train-front": TrainFront,
  "tree-pine": TreePine,
  "thumbs-up": ThumbsUp,
  timer: Timer,
  trophy: Trophy,
  umbrella: Umbrella,
  users: Users,
  watch: Watch,
  waypoints: Waypoints,
  wifi: Wifi,
  wrench: Wrench,
  zap: Zap,
});
